{
  "fzf-help" = "echo 'ctrl+option (f -> files, l -> log, s -> status, r -> history, v -> variables, e -> process id)'";
  "cd.." = "cd ..";
  ".." = "cd ../";
  "..." = "cd ../../";
  "cdr" = "ranger";
  "ran" = "ranger";
  "start-nebula" = "sudo nebula -config /etc/nebula/config.yaml";
  f = "fish";
  ni = "pushd ~/nixfiles";
  strip = "pbpaste | pbcopy";
  clean = "pbpaste | pbcopy";
  pwdcp = "pwd | pbcopy";
  cdc = "pwd | pbcopy";
  cdp = "cd (pbpaste)";
  jsonvalidate = "pbpaste | jq";
  dotfiles = "cd ~/nixfiles";
  nixfiles = "cd ~/nixfiles";
  pkgs = "$EDITOR ~/nixfiles/modules/common.nix";
  Source = "cd ~/Source";
  flushdns = "sudo dscacheutil -flushcache; sudo killall -HUP mDNSResponder";
  amend = "git commit --amend --no-edit";
  less = "bat";
  diff = "diff -u";
  g = "git status -s";
  gcp = "git cherry-pick";
  gui = "gitui";
  gau = "git add -u";
  gp = "git pull --rebase";
  gprom = "git pull --rebase origin/main || git pull --rebase origin/master";
  grom = "git rebase origin/main || git rebase origin/master";
  grot = "git rebase origin/trunk";
  grod = "git rebase origin/dev";
  gpom = "git push -u origin main || git push -u origin master";
  grc = "git rebase --continue";
  gcm = "git checkout main || git checkout master || git checkout trunk";
  gss = "git stash save";
  gsp = "git stash pop";
  gsl = "git stash list";
  grh = "git reset --hard";
  gclean = "git remote prune origin; git branch --merged | grep -v -E '(master|main|dev|release|hotfix|trunk|prod)' | xargs -n 1 git branch -d";
  gcleanall = "git remote prune origin; git branch | grep -v -E '(master|main|dev|release|hotfix|trunk|prod)' | xargs -n 1 git branch -D";
  gs = "git show";
  gf = "git fetch --all";
  gb = "git branch -a";
  gcop = "git branch --sort=-committerdate | fzf --header 'Checkout Recent Branch' --preview \"git diff {1} --color=always\" --pointer=\"->\" | xargs git checkout";
  gme = "git status --short | choose -1 | sk | xargs $EDITOR";
  gco = "git checkout";
  gcob = "git checkout -b";
  grv = "git remote -v";
  ga = "git add";
  gap = "git add -p";
  gd = "git diff -a";
  gdw = "git diff -w ";
  gdc = "git diff --cached";
  gdcw = "git diff --cached -w";
  ghb = "gh browse";
  lg = "lazygit";
  gl = "lazygit log";
  lad = "lazydocker";
  lac = "lazycli";
  x = "z";
  xi = "zi";
  pd = "popd";
  br = "broot -c:open_preview";
  lt = "broot -c:open_preview";

  ealias = "$EDITOR ~/nixfiles/modules/shell/fish.nix";
  ea = "$EDITOR ~/nixfiles/modules/shell/fish.nix";
  tree = "eza --tree";
  l = "eza -lh  --icons --group-directories-first --classify";
  ltree = "eza -lh  --icons --group-directories-first --classify --tree --color=always | bat";
  ll = "eza -lah --icons --group-directories-first --classify";
  la = "eza -la  --icons --group-directories-first --classify";
  ls = "eza";
  cat = "bat -p";
  icat = "wezterm imgcat";
  ehosts = "sudo $EDITOR /etc/hosts";
  memory = "ps -A u | sort -k 4 -r | head";
  top = "btm";

  port = "lazycli -- 'lsof -i -P -n | grep -E \"(LISTEN|COMMAND)\"'";
  wine = "lazycli -- 'lsof -i -P -n | grep -E \"(node|nginx)\" || echo \"No node or nginx servers running\"'";

  tm = "tmux -2 new -s '(basename '(pwd)')'";
  tma = "tmux -2 attach -d -t";
  tmk = "tmux kill-session -t";
  tml = "tmux list-sessions";
  tmn = "tmux new-session -t base";
  tmr = "tmux rename-session -t";
  tmux = "tmux -2";

  rust = "echo \"Use rr instead:\" && rust-script";
  rr = "rust-script";
  ru = "rust-script";
  cb = "cargo build";
  cr = "cargo run";

  kk = "kubectl";

  npmi = "npm install";
  npmb = "npm run build";
  npms = "npm start";
  npmt = "npm test";
  npml = "npm run lint";

  pnpmi = "pnpm i";
  pnpmr = "pnpm run";
  pnpmb = "pnpm run build";
  pnpmt = "pnpm test";
  pnpms = "pnpm start";
  pnpml = "pnpm run lint";

  xcd = "cd (xplr --print-pwd-as-result)";
  xp = "cd (xplr --print-pwd-as-result)";
  xd = "cd (xplr --print-pwd-as-result)";

  he = "hx";
  vi = "$EDITOR";
  vim = "nvim";
  vimrc = "nvim ~/nixfiles/modules/editors/nvim.nix";
  hxrc = "$EDITOR ~/nixfiles/modules/editors/helix.nix";
  wzrc = "$EDITOR ~/nixfiles/modules/shell/wezterm/wezterm.lua";
  merge = "open -n -a \"Sublime Merge\" .";
  bane = "bane2";
  c = "code .";
  no = "pushd ~/notes && hx ./ && popd";
  ob = "pushd ~/obsidian-notes && hx && popd";
  nt = "pushd ~/notes";

  md2j = "pandoc --to jira | pbcopy";
  wiki = "pushd ~/Source/wiki/docs && $EDITOR";
}
